Repository youssef-ahmmed/simple_shell, pull requests merged in 2023-05, with the labels that each got.

#3 feat-tasks-2-implement_tasks_partner_2
  builtin_commands1.c
  builtin_commands2.c
  check_builtin_commands.c
  execute.c
  free.c
  get_environment.c
  get_inputs.c
  helpful_methods.c
  path.c
  print_prompt.c
Labels: enhancement

#4 feat-tasks-1-implement_tasks_partner_1
  README.md
  imgs/working_shell.png
  print_to_stdout.c
  shell.c
  shell.h
  signal_handler.c
  tokenization.c
Labels: documentation, enhancement

#7 Remove all modules because of bugs
  builtin_commands1.c
  builtin_commands2.c
  check_builtin_commands.c
  execute.c
  free.c
  get_environment.c
  get_inputs.c
  helpful_methods.c
  path.c
  print_prompt.c
  print_to_stdout.c
  shell.c
  shell.h
  signal_handler.c
  tokenization.c
Labels: bug

#8 Implement remaining tasks with almost working
  env_operations1.c
  env_operations2.c
  finders.c
  get_input.c
  info_util.c
  input_validation.c
  list_utils1.c
  list_utils2.c
  memory_utils.c
  path_handling.c
  print_helpers1.c
  shell.h
Labels: enhancement

#9 Implement remaining tasks with almost working
  print_helpers2.c
  replace_helpers.c
  shell.c
  shell_builtins1.c
  shell_builtins2.c
  shell_loop.c
  string_utils1.c
  string_utils2.c
  string_utils3.c
  tokenizer.c
Labels: enhancement
